DjangoWebProject1/DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views




from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    # Examples:
    url(r'^$', app.views.home),
    url(r'^admin/', admin.site.urls),

    url(r'^resume/', app.views.resume_view),
    url(r'^portfolio/', app.views.portfolio_view),


    url(r'^interview_questions/$', app.views.InterviewView.as_view(), name='interview_questions'),

    url(r'^(?P<pk>[0-9]+)/$', app.views.SingleQuestionView.as_view(), name='detail'),      
    
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),

    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

  
]

DjangoWebProject1/app/models.py
"""
Definition of models.
"""

from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)  



    def __str__(self):
        return self.question_text



class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()
    
    def __str__(self):
        return self.answer

DjangoWebProject1/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

DjangoWebProject1/app/views.py
"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.template import RequestContext
from datetime import datetime

from .models import Question

from django.views import generic



def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/index.html',
        {
            'title':'Home Page',
            'year':datetime.now().year,
        }
    )

def resume_view(request):
    #image_data = open("static/app/BDreslerResume.png", "rb").read()  
    return render(request, 'app/resume.html')

def portfolio_view(request):
    return render(request, 'app/portfolio.html')


class InterviewView(generic.ListView):
    model = Question
    template_name='app/interview_questions.html'

    def get_context_data(self, **kwargs):
        context = super(InterviewView, self).get_context_data(**kwargs)
        context['random_question_list'] = Question.objects.all().order_by('?')[:3]
        context['full_question_list'] = Question.objects.all()
        return context


class SingleQuestionView(generic.DetailView):
    model = Question
    template_name = 'app/single_question.html'

    def get_context_data(self, **kwargs):
        context = super(SingleQuestionView, self).get_context_data(**kwargs)     
        context['full_question_list'] = Question.objects.all()
        return context

DjangoWebProject1/app/templates/app/index.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Home Page {% endblock %}



{% block content %}



<div class="container" style="height: 100vh">
    <p>
    <br /> <b>Intro</b><br />
    <img src="{% static "/app/profile.png" %}" alt="profile" width="200" height="200">
     
    If you are visiting this page, you probably already know a bit about me. I created this page to teach myself web development and to serve as supplementary information about myself. 
    This page is built using Django Python web framework and hosted on the Microsoft Azure cloud platform. For lack of better inspiration, it can be considered it my own custom LinkedIn page where I can customize 
    the content to reflect my own style. 
    <br /><br />

    <b>Growing Up</b><br />
    I am from Longmont Coloardo and attended Niwot High School. My grew up playing sports and always had a knack for math and science. 
    My sports interests ranged from soccer, to basketball, to my more lasting ventures in hockey and baseball. By high school, I had relegated my time to 
    baseball, hockey, and my schoolwork. I'd become a favorite student among my teachers and a top student while taking AP college credit courses. 
    <br /><br />

    <b>College</b><br />
    During my senior year of High School, I joined a showcase baseball team out of Denver. I was nothing spectacular and inconsistent, I found myself with 
    a handful of scholarship offers from assorted smaller schools. I took an offer from Scottsdale Community College here in Arizona. I was excited to start fresh and 
    and supported the notion of spending my first two years at a community college. My sophomore year I made the starting rotation as a pitcher. It was 
    only after three starts I endured four cervical fractures in a rock climbing incident and was sidelined for over three months. I never earned my starting position 
    back and instead focused on my studies.
    <br /><br />
    After my time at Scottsdale, I had to decided to pursue Nuclear Engineering. However I was happy here in Arizona and more importantly out of state tuition was unreasonable. I decided to attend 
    Arizona State University and pursue the next best thing, Chemical Engineering. My classes were small, somewhere between 30 and 50 people and dwindled every year. We spent 
    countless hours in "the cave" where we wrote writing hundreds of pages of lab reports and trying to fit equations together like a game of sudoku. I graduated in May 2012 with honors 
    and near the top of my class. 
    <br /><br />

    <b> Work and Career </b><br />
    While at ASU, no longer a student athlete, I worked part time at Big 5 Sporting Goods as a sales associate. 
    I'm proud of this work because it had a monumental impact on who I am today. Working retail is humbling and teaches the importance of interpersonal skills. 
 
    <br /><br />
    After graduation it was time to pursue a career. I joined Honeywell in October 2012 as a Remote Service Engineer. The prior employee had switched groups 
    and there was an urgent vacancy. When I joined I was the sole person in the Americas supporting products I was simultaneously learning how to use. Thankfully, I had great support from 
    my manager, the prior employee, and the support group based out of Bangalore. 
    <br /><br />
    Years later, I still work in the same area. The landscape is a bit different and the applications have evolved. My support services has led me to learn the detailed working 
    of several Honeywell products used as peripherals to my applications. I've even ventured into development work in order to fill gaps and productivity issues.
    <br /><br />
    I look forward to the future and I'm excited to take on new and exciting challenges.
</p>



<br>
</div>

{% endblock %}







			

DjangoWebProject1/app/templates/app/interview_questions.html
{% extends 'base.html' %}
{% load static %}


{% block content %}




<div class="container">
    
           <br />

    {% if random_question_list %}

    <div class="panel-heading">
        <h4>Random Questions</h4>
    </div>
</div>



 {% for question in random_question_list %}
<div class="container">

  <ul class="list-group">

    <li class="list-group-item">Q: {{ question }}
    <br>
        {% for answer in question.answer_set.all %}
        A: {{answer.answer}}<br>
        {% endfor %}
    </li>

  </ul>
</div>

{% endfor %}


</ul>
{% else %}
<p>No questions loaded.</p>
{% endif %}



<div class="container" style="height: 100vh">
    <div class="panel-heading">
        <h4>Select Another Question Below.</h4>
       </div>

        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                     <h4 class="panel-title">
                     <a data-toggle="collapse" href="#collapse1">Click Here For More Questions</a>
                        </h4>
                </div>
             <div id="collapse1" class="panel-collapse collapse">
        <ul class="list-group">
            {% for question in full_question_list %}
            <li class="list-group-item"><a href="{% url 'detail' question.id %}">{{ question }}</a></li>

        </ul>
          {% endfor %}
      </div>
    </div>
  </div>
</div>





{% endblock %}



			

DjangoWebProject1/app/templates/app/portfolio.html
{% extends 'base.html' %}
{% load static %}
 



{% block content %}




<div class="container" style="height: 100vh">

    <br />

<p> Below are a handful of recent projects or achievements. 
    I chose to be very non-descript as to emphasize the relevant skills rather than details of the work.  </p>




	  <div class="row">

		<div class="col-sm-6" font-color="blue">
		<h4>Report Optimization</h4>
        <p><b>Relevant: SQL, Visual Basic, JavaScript </b> <br />
            Vastly increased the efficiency in data ingestion and report generation. 
            Reports used SQL queries that often were inefficient and using massive iterative approaches. 
            By rethinking the queries using the same schema some report queries were cut from hours to minutes.
            The reports database contained over a decade of accumulation. 
            By removing unused report from the database of current customers, the load on the parser was significantly decreased.
            </p>
		</div>

		<div class="col-sm-6">
		<h4>Customer Support Focal</h4>
            <p><b>Relevant: Customer Management, Communication</b> <br />
            Support focal for up to five seperate application valued at hundreds of thousands in support contracts. 
            Earned respect of both customer and internal contacts to an extent I am often contacted in regards to 
            applications I have no relevance to.
            </p>
		</div>
        
	  </div>
    
        <br />

      <div class="row">

		<div class="col-sm-6">
		<h4>Productivity Tools</h4>
        <p><b>Relevant: Python, C++, Excel</b> <br />           
           Using Python3, automated repetivive tasks such as file management, data mining, and report delivery. 
           This automation was used to complete tasks more accurately and quickly than had been done in the past. 
           Monthly report delivery had been reduced from days to hours and created a platform for expansion into
           including useful KPIs and additional information pulled directly from the database in the delivery.           
         </p>
		</div>

		<div class="col-sm-6">
		<h4>Data File Analytics</h4>
       <p><b>Relevant: Python, RegEx, Excel</b> <br />
           Developed applications using Python3 to help diagnose application errors. 
           This included the analysis of spreadsheets, xml files, and databases using primarily pandas dataframes.
           Our encrypted xml data files contained no discernable schema or standalone useful information. 
           By parsing the xml files using regex batch anlyses and cross referencing with configs that serve as a decoder,
           I was able to analyze raw data files in a way that had never been done.
         </p>
		</div>

        
	  </div>

        <br />
      
      <div class="row">

		<div class="col-sm-6">
		<h4>Domain Administration / Migration</h4>
         <p><b>Relevant: Server Management, Windows, VMWare </b> <br />
        Application owner for several servers and responsible for application health as well as upgrades. 
        Migrated physical machines to virtual machines with updated operating systems.
        Domain administrator in charge of permissions and account management for employee access to applications.
            </p>
		</div>

		<div class="col-sm-6">
		<h4>Web Development</h4>
        <p><b>Relevant: Python, Django, JavaScript, HTML, CSS </b> <br />
        Developed fully functional prototype for league kickball announcements, registration, and discussion feed. 
        Contained linked models for leagues, teams, and players and was designed with ease of use for the administrator in mind.
        Used a REST api for all form submissions. 
        Included paypal integration using the secure paypal API and customer forms to ensure payment during registration.
            </p>
		</div>

        
	  </div>
    

   
	</div> 






{% endblock %}







			

DjangoWebProject1/app/templates/app/resume.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Resume {% endblock %}



{% block content %}
{% load static %}
<center>
   <div class="container" style="height: 100vh">

       <br />
  
   <img src="{% static "/app/BDreslerResume.png" %}" alt="I fail at deploying static files" width="100%"  >
      
 </div>
 
       
</center>

{% endblock %}







			

DjangoWebProject1/app/templates/app/single_question.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}





<div class="container" style="height: 100vh">

    <br />

    <div class="panel-heading">
        <h4>{{ question.question_text }}</h4>
    </div>




{% for n in question.answer_set.all %}


  <ul class="list-group">

    <li class="list-group-item">
        {{n}}       
    </li>

  </ul>

{% endfor %}

    <br />


     <div class="panel-heading">
       <h4>Other Questions.</h4>
    </div>

  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="#collapse1">Click Here For More Questions</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <ul class="list-group">
            {% for question in full_question_list %}
            <li class="list-group-item"><a href="{% url 'detail' question.id %}">{{ question }}</a></li>

        </ul>
          {% endfor %}
      </div>
    </div>
  </div>
 </div>





{% endblock %}



			

DjangoWebProject1/app/templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
  <title>BDresler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<style>
.container {
    background-image: url("{% static "/app/white-canvas-background.png" %}");
    background-size: 100%;
    background-repeat: repeat;    
    overflow: auto;
}
.container-full {
  margin: 0 auto;
  background-size: 100%;  
  background-image: url("{% static "/app/background-full.jpg" %}");
  background-repeat: repeat;
  height: 100vh; 
  overflow: auto;

}

img {
    float: right;
    margin: 0 0 10px 10px;
} 

</style>


<body>
<div class="container-full">
  <div class="container" style="background:#e6e6e6">
  <h3>Welcome </h3>
   <!-- <p> Thank you for visiting my site. </p>-->
  <p></p>
  <ul class="nav nav-tabs nav-justified">    
    <li><a href=/>Home</a></li>
    <li><a href=/resume/>Resume</a></li>
    <li><a href=/interview_questions/>Questions</a></li>
    <li><a href=/portfolio/>Portfolio</a></li>
  </ul>
        
</div>



  
 {% block content %}
{% endblock %}




</body>
</html>